package Constants;

public class GameConstants {
    public static final String CHOOSE_TOSHIFT = "Напиши имя питомца, к которому хочешь перейти.";
    public static final String NO_MONEY = "Недостаточно средств!";
    public static final String BOOSTED = "Ускорено✅";
    public static final String UNKNOWN_COMMAND = "Я не знаю такой команды!";
    public static final String ERROR_MESSAGE = "У вас еще нет питомца! Напишите /create, чтобы создать его.";
    public static final String PET_EAT = " поест и будет сыт.";
    public static final String PET_PLAY = " рад, что вы поиграли с ним.";
    public static final String PET_WALK = " рад прогулке.";
    public static final String PET_STROKE = " счастлив, что вы погладили его.";
    public static final String PET_SLEEP = " лег спать.";
    public static final String START = "Привет, я PetSim бот! Напиши /help, чтобы узнать, что я умею делать.";
    public static final String STOP = "Приходи создать питомца в другой раз, я буду ждать!";
    public static final String HERE = " теперь здесь";
    public static final String SLEEPING = " пока спит!";
    public static final String EATING = " еще не поел!";
    public static final String WALKING = " еще не вернулся с прогулки.";
    public static final String CHOOSE_TO_BUY = "Пиши /shop, чтобы узнать, что можно купить для ";
    public static final String BUY_NO_HUNGER = "Теперь вашему питомцу требуется меньше времени, чтобы поесть!";
    public static final String BUY_NO_NEED = "Теперь вашему питомцу требуется меньше времени на прогулку!";
    public static final String BUY_MAX_ENERGY = "Теперь вашему питомцу требуется меньше времени на сон!";
    public static final String BUY_MORE_MONEY = "Теперь за каждое действие вы будете получать 2 монеты!";
    public static final String BUY_ALL = "Теперь у вашего питомца есть все улучшения!";
    public static final String FINISHED_WALKING = " нагуглялся и готов общаться.";
    public static final String FINISHED_SLEEPING = " выспался и ждет тебя!";
    public static final String FINISHED_EATING = " уже поел!";
    public static final String YOUR_PET_IS_DYING = " умирает! Позаботься о нем!";
    public static final String NOT_WANT_EAT = " пока не голоден!";
    public static final String NOT_WANT_SLEEP = " не хочет спать!";
    public static final String NOT_WANT_PLAY = " не хочет играть!";
    public static final String NOT_WANT_WALK = " не хочет гулять!";
    public static final String NOT_WANT_STROKE = " пока не хочет, чтоб ты его гладил!";
    public static final String ALREADY_BOUGHT_IMPROVEMENT = "У тебя уже куплено это улучшение!";
    public static final String ALREADY_BOUGHT_SKIN = "У тебя уже куплен этот скин!";
    public static final String SUCCESSFUL_BUY_SKIN = "Скин куплен!";
    public static final String SUCCESSFUL_CHANGE_SKIN = "Скин изменен!";
    public static final String NO_MORE_SKINS = "У тебя нет других скинов!";
    public static final String DOG = "Dog";
}
